name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential git zip unzip \
          openjdk-17-jdk wget curl libncurses5 libffi-dev \
          libssl-dev libsqlite3-dev zlib1g-dev libbz2-dev \
          libreadline-dev liblzma-dev

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer

    - name: Initialize buildozer
      run: buildozer init

    - name: Override spec file with custom one
      run: cp buildozer.spec ./

    - name: Build the APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-quote-app-apk
        path: bin/*.apk
