name: Build Android App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build APK with Buildozer
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip git python3-pip build-essential \
            libssl-dev libffi-dev python3-dev python3-setuptools \
            libsqlite3-dev libgmp-dev libbz2-dev zlib1g-dev \
            libncurses5-dev libncursesw5-dev libreadline6-dev \
            libsqlite3-dev libgdbm-dev libc6-dev libbz2-dev \
            libffi-dev liblzma-dev libjpeg-dev libfreetype6-dev \
            libgl1-mesa-dev libgles2-mesa-dev libpng-dev \
            libxml2-dev libxslt1-dev libudev-dev libusb-1.0-0-dev \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
            libtiff5-dev libsmpeg-dev libx11-dev libxrandr-dev libxinerama-dev \
            libxcursor-dev libxi-dev ffmpeg openjdk-17-jdk

        pip install --upgrade pip
        pip install buildozer cython

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: bin/*.apk
