name: Build APK with Buildozer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential git zip unzip \
          openjdk-17-jdk wget curl libffi-dev \
          libssl-dev libsqlite3-dev zlib1g-dev libbz2-dev \
          libreadline-dev liblzma-dev

    - name: Install Buildozer and Cython
      run: |
        python3 -m pip install --upgrade pip
        pip install --user buildozer Cython

    - name: Add buildozer to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Initialize Buildozer
      run: buildozer init

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: built-apk
        path: bin/*.apk
