name: Build APK with Buildozer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip
        pip install --upgrade pip setuptools wheel
        pip install cython virtualenv buildozer

    - name: Accept Android SDK Licenses
      run: |
        mkdir -p ~/.android
        echo '8933bad161af4178b1185d1a37fbf41ea5269c55' > ~/.android/repositories.cfg
        yes | sdkmanager --licenses || true

    - name: Initialize Buildozer
      run: |
        buildozer init
        cp buildozer.spec buildozer.spec.bak
        mv buildozer.spec.bak buildozer.spec

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: quoteapp.apk
        path: bin/*.apk
