name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            python3-dev \
            libffi-dev \
            libssl-dev \
            libjpeg-dev \
            zlib1g-dev \
            libncurses5-dev \
            libsqlite3-dev \
            libgdbm-dev \
            libc6-dev \
            libbz2-dev \
            libreadline-dev \
            libncursesw5-dev \
            libffi-dev \
            liblzma-dev \
            lzma \
            libgl1-mesa-dev

      - name: Install buildozer
        run: |
          pip install --upgrade pip
          pip install cython==0.29.36
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-kivy-apk
          path: bin/*.apk
