name: Android APK Build with Buildozer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04  # Use Ubuntu 22.04 instead of 24.04 for better compatibility

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install required system packages
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-11-jdk \
          python3-pip \
          libncurses5:i386 libstdc++6:i386 \
          libgtk2.0-0:i386 libpangox-1.0-0:i386 \
          libpangoxft-1.0-0:i386 libidn11:i386 \
          libudev-dev

    - name: Install buildozer and dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install buildozer cython

    - name: Initialize Buildozer spec
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4  # ✅ latest version
      with:
        name: built-apk
        path: bin/*.apk
