name: Android APK Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          check-latest: true

      - name: Install Build Essentials and Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            libncurses5 \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            libjpeg-dev \
            libpng-dev \
            zlib1g-dev \
            liblzma-dev \
            libtiff-dev \
            pkg-config \
            autoconf \
            automake \
            libtool \
            python3-dev

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install buildozer Cython

      - name: Check if buildozer.spec exists
        id: check_spec
        run: |
          if [ -f buildozer.spec ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Initialize Buildozer (only if no buildozer.spec)
        if: steps.check_spec.outputs.exists == 'false'
        run: buildozer init

      - name: Build APK
        run: buildozer -v android debug
